### ISSUE TITLE
应用太多时（top: pid limit (20) exceeded）

### ISSUE THREAD

**Issue by yoara** [oldratlee/useful-scripts#100]
```sh
top: pid limit (20) exceeded
Error: No java process found!

top -H -b -d 0.5 -n 2 -p 19464,25398,48880,49022,49405,49745,57525,59789,59879,59920,61524,62568,67854,68740,68811,99119,120821,121525,155445,156060,162058,171001,198278,205466,205566,222012,239165,277192,278971,300070,303922,335372,346314,347193,353547,365089,368938,379770,419686,424287,441339,451103
top: pid limit (20) exceeded
```

建议`pid`太多时做截取

**Comment by oldratlee** [comment]
从出错信息上看，`pid`个数是`top`命令的限制（不是`show-busy-java-threads`的限制）；
为什么这样的限制是合理的，要调查一下了。

> 建议`pid`太多时做截取

像`pid`个数自动截取这样的事，不应该做； @yoara
`top`命令也没有这样做的，而是报错并停止执行。

错误不能默默的被吃掉，否则用户以为没问题没有出错（并在这样错误前提下接着误做了很重要的事），结果并不是。

> 9. 出错决不能无声无息地忽略。
>    - 除非明确地说明了是无声无息的。
>
> 摘自 [《Python之禅》](https://github.com/oldratlee/translations/blob/master/python-philosophy/README.md#python%E5%93%B2%E5%AD%A6)


-------------

@yoara 问一下，你是什么场景 需要设置 大量的`pid`？

**Comment by JHWen** [comment]
您的邮件我已收到，谢谢！
