### ISSUE TITLE
/dev/stdout: Permission denied

### ISSUE THREAD

**Issue by wushengde** [oldratlee/useful-scripts#114]
execute this show-busy-java-threads prompt  "show-busy-java-threads: line 152: /dev/stdout: Permission denied" .

**Comment by oldratlee** [comment]
@wushengde please give your run infos, like

- run command(e.g. the whole command line; via sudo?)
- run env(e.g. in docker?)

------

and run with bash trace output:

```bash
$ /bin/bash -x <original command line>
# trace outputs...
```

if you are familiar with bash, you can troubleshoot the problem and find more reason info.

**Comment by oldratlee** [comment]
closed.

continue discussion if more info provided.

**Comment by lkun** [comment]
你好：
你的邮件我会尽快看的啦！！！

**Comment by JHWen** [comment]
您的邮件我已收到，谢谢！

**Comment by oldratlee** [comment]
commit "use file descriptor number instead of `/dev/std*`(dc5b239b24472fdafe556eac265874955e3ff79e)" should fix this issue. @wushengde
