### ISSUE TITLE
语法不对，请问怎么解决，是直接wget到服务器执行的

### ISSUE THREAD

**Issue by JeanseLam** [oldratlee/useful-scripts#115]
![image](https://user-images.githubusercontent.com/13899906/178441937-40573da2-fd9a-4013-8188-057aef860c19.png)

**Comment by oldratlee** [comment]
排查信息不完整。用最新版本再试试。

- 如何获取的过程，哪个文件版本
- bash 版本
- 等等

一般是`bash`版本或是`shell`不对的问题。

**Comment by lkun** [comment]
你好：
你的邮件我会尽快看的啦！！！

**Comment by JHWen** [comment]
您的邮件我已收到，谢谢！
