### ISSUE TITLE
show-busy-java-threads:why update 2 times

### ISSUE THREAD

**Issue by NS-FDF** [oldratlee/useful-scripts#116]
![图片](https://github.com/oldratlee/useful-scripts/assets/49178586/b3bfbb0e-3ef6-4c9e-83b5-47fe87cac62c)

**Comment by lkun** [comment]
你好：
你的邮件我会尽快看的啦！！！

**Comment by JHWen** [comment]
您的邮件我已收到，谢谢！

**Comment by oldratlee** [comment]
> why `top` update 2 times

because the content of the first update is not the cpu usage between interval.

more info see the man of `top`. @NS-FDF

**Comment by NS-FDF** [comment]
>

**Comment by NS-FDF** [comment]
> > why `top` update 2 times
> 
> because the content of the first update is not the cpu usage between interval.
> 
> more info see the man of `top`. @NS-FDF

THX
