### ISSUE TITLE
linux中添加回收站(将rm改为mv)

### ISSUE THREAD

**Issue by darker12356** [oldratlee/useful-scripts#118]
您好，请问目前有或者计划编写一个linux回收站功能嘛
当rm删除文件或目录时，将它们移动到当前用户的某个目录下
例：rm -f /data/file.log   ==>  mv /data/file.log /tmp/$(date +%F)/

**Comment by JHWen** [comment]
您的邮件我已收到，谢谢！

**Comment by lkun** [comment]
你好：
你的邮件我会尽快看的啦！！！

**Comment by oldratlee** [comment]
@darker12356 
删除文件到（系统）回收站，已经有这样的功能实现了；
这个库不再实现了，可以找一下。

删除到系统回收站的实现，不同`OS`不同。

个人有安装这样的工具，但用得不多 😂
