### ISSUE TITLE
show-busy-java-threads： jdk21没有展示stack信息

### ISSUE THREAD

**Issue by jianyun** [oldratlee/useful-scripts#120]
jdk21  

```sh
+ printf '\e[1;%sm%s\e[0m\n' 31 'Error: No java process found!'
Error: No java process found!
```

**Comment by jianyun** [comment]
alpine 基础镜像

**Comment by oldratlee** [comment]
@jianyun 


- 能确认有`Java`进程吗？给一下检查内容
- 另外可以给一下你的
  - 运行方式 
  - 和 debug运行输出（`bash -x show-busy-java-threads`）

**Comment by jianyun** [comment]
![20240218094257541](https://github.com/oldratlee/useful-scripts/assets/13871143/b488e004-5664-4760-9959-48ba4261439c)
[Alpine_jdk21.txt](https://github.com/oldratlee/useful-scripts/files/14320772/Alpine_jdk21.txt)
  
[centos_jdk21.txt](https://github.com/oldratlee/useful-scripts/files/14320774/centos_jdk21.txt)
升级了新的脚本还是获取不到

**Comment by jianyun** [comment]
![20240218094730172](https://github.com/oldratlee/useful-scripts/assets/13871143/ecc7eb6b-b840-4c55-82ef-58eb86c7eeaa)

**Comment by oldratlee** [comment]
解决了 Java 21 没有 stack信息问题：

- **注意** 使用分支[**`release-2.x`**](https://github.com/oldratlee/useful-scripts/commits/release-2.x) @jianyun 
  - 缺省开发分支还在开发中，改动比较多
- release `v2.5.3`
  - https://github.com/oldratlee/useful-scripts/releases/tag/v2.5.3

**Comment by jianyun** [comment]
点赞，可以了
