### ISSUE TITLE
ubuntu 系统 jdk21 统计不了 busy 栈

### ISSUE THREAD

**Issue by jianyun** [oldratlee/useful-scripts#121]

**Comment by lkun** [comment]
你好：
你的邮件我会尽快看的啦！！！

**Comment by oldratlee** [comment]
@jianyun 更新一下 试试，参见 issue：

- https://github.com/oldratlee/useful-scripts/issues/120#issuecomment-1950964013

> 解决了 Java 21 没有 stack信息问题：
>
> - **注意** 使用分支[**`release-2.x`**](https://github.com/oldratlee/useful-scripts/commits/release-2.x) @jianyun 
>   - 缺省开发分支还在开发中，改动比较多
> - release `v2.5.3`
>   - https://github.com/oldratlee/useful-scripts/releases/tag/v2.5.3

**Comment by jianyun** [comment]
上个问题也是我提的，已经更新2.5.3，centos2024年6月停止维护，最近再处理基础镜像替换。当前centos jdk21可以统计，ubuntu的还是不行

**Comment by oldratlee** [comment]
> 上个问题也是我提的，已经更新2.5.3，centos2024年6月停止维护，最近再处理基础镜像替换。当前centos jdk21可以统计，ubuntu的还是不行

@jianyun 收到。可以给一下你的

- 运行方式，运行输出/结果
- 环境信息
  - `uname -a`
  - `bash --version`
  - `java -version`
  - ...
- 和`debug`运行输出（`bash -x show-busy-java-threads`）

----

我自己是在`Ubuntu 20`上测试 OK；需要更多你的信息。

**Comment by jianyun** [comment]
[ubuntu-debug.txt](https://github.com/oldratlee/useful-scripts/files/14580510/ubuntu-debug.txt)

**Comment by oldratlee** [comment]
运行代码 与 `v2.5.3`的代码 不一致。如

- `sed`正则（`sed_script`）不同，不是`/ nid=($threadId0x|$threadId) /`。
- 运行代码的`sed`没有`-r`选项。

可以检查一下你运行的代码文件。 @jianyun 
（如果修改实现则需要自己迭代排查一下；我不方便看你的源码实现）

### 更多代码的对比信息

`ubuntu-debug.txt`的内容：

```bash
+ local 'sed_script=/ nid=0x6 /,/^$/ {
                /^$/d; p # delete end seperator line
            }'
# Line 815
+ sed '/ nid=0x6 /,/^$/ {
                /^$/d; p # delete end seperator line
            }' -n /tmp/show-busy-java-threads_2024-03-13_09:04:32.227441271_16478_73152/2024-03-13_09:04:32.227441271_1_jstack_6
```

`v2.5.3`的代码：

https://github.com/oldratlee/useful-scripts/blob/cfcbeb345058aaf668130d29a000bfcf89745af0/bin/show-busy-java-threads#L579-L583

**Comment by jianyun** [comment]
> 运行代码 与 `v2.5.3`的代码 不一致。如
> 
> * `sed`正则（`sed_script`）不同，不是`/ nid=($threadId0x|$threadId) /`。
> * 运行代码的`sed`没有`-r`选项。
> 
> 可以检查一下你运行的代码文件。 @jianyun （如果修改实现则需要自己迭代排查一下；我不方便看你的源码实现）
> 
> ### 更多代码的对比信息
> `ubuntu-debug.txt`的内容：
> 
> ```shell
> + local 'sed_script=/ nid=0x6 /,/^$/ {
>                 /^$/d; p # delete end seperator line
>             }'
> # Line 815
> + sed '/ nid=0x6 /,/^$/ {
>                 /^$/d; p # delete end seperator line
>             }' -n /tmp/show-busy-java-threads_2024-03-13_09:04:32.227441271_16478_73152/2024-03-13_09:04:32.227441271_1_jstack_6
> ```
> 
> `v2.5.3`的代码：
> 
> https://github.com/oldratlee/useful-scripts/blob/cfcbeb345058aaf668130d29a000bfcf89745af0/bin/show-busy-java-threads#L579-L583

抱歉，我的疏忽，构建机环境版本不一致
