### ISSUE TITLE
[1] Fail to jstack busy(48.0%) thread(32231/0x7de7) stack of java process(32170) under user(root).

### ISSUE THREAD

**Issue by MoonLionK** [oldratlee/useful-scripts#123]
[root@Server-b1e1af54-b199-4a87-92fa-286cedc4693d docker]# ./show-busy-java-threads 
./show-busy-java-threads:行114: : 未找到命令
[1] Fail to jstack busy(48.0%) thread(32231/0x7de7) stack of java process(32170) under user(root).

./show-busy-java-threads:行114: : 未找到命令
[2] Fail to jstack busy(0.0%) thread(32170/0x7daa) stack of java process(32170) under user(root).

java服务使用dockerCompose安装

**Comment by lkun** [comment]
你好：
你的邮件我会尽快看的啦！！！

**Comment by oldratlee** [comment]
@MoonLionK 如果是`jstack`命令找不到的话，需要自己设置好环境。

`show-busy-java-threads`会从`JAVA_HOME`和`PATH`上找`jstack`命令；也支持选项参数以显式指定`jstack`命令的路径。

----


- 是完整的运行&出错信息吗？如果不是给一下完整的出错信息
  - debug运行输出：`bash -x show-busy-java-threads ...`
- 确定一下使用的`show-busy-java-threads`版本，给一下对应的commit/tag

**Comment by lkun** [comment]
你好：
你的邮件我会尽快看的啦！！！
