### ISSUE TITLE
为何执行不过去呢？脚本需要什么参数吗

### ISSUE THREAD

**Issue by wanghaile** [oldratlee/useful-scripts#57]
```bash
➜  useful-scripts git:(release) sh show-busy-java-threads.sh  -c 10
head: illegal option -- -
usage: head [-n lines | -c bytes] [file ...]
```

**Comment by oldratlee** [comment]
`show-busy-java-threads.sh`不支持Mac系统，原因是：

Mac下`ps`命令不能列出线程信息，在Mac下实现不了。更多信息参见 #33 

## PS

不要自己去指定`sh`的方式去执行脚本 @wanghaile (这个是坏习惯 😄 ) ：

1. 脚本已经是可执行的，操作更简单些。
    - 在里面指定的是`bash`，
    - 脚本中总是指定上确定的`shell`（如`bash`）是最佳实践： `#!/bin/bash`。
3. 不同的`shell`（sh、bash、zsh、fish、csh、tcsh、ksh、ash、dash……）有各种差异，**深坑勿入**。
    - 目前主流的是`bash`/`zsh`。
    - 更多`shell`的信息 参见 https://en.wikipedia.org/wiki/Comparison_of_command_shells
4. `sh`可能是个符号链接，可能链接到不同的`shell`，如有的`Ubuntu`版本，`sh`是链接到`dash`的。


#### 推荐直接执行的方式：

```bash
wget https://github.com/oldratlee/useful-scripts/raw/dev-2.x/bin/show-busy-java-threads
chmod +x show-busy-java-threads
./show-busy-java-threads
```

## PPS

上面出错的信息是指，`mac`的`head`命令 不支持`--lines`选项。

**Comment by wanghaile** [comment]
好的，谢谢指点

**Comment by oldratlee** [comment]
在文档中，加上了 脚本支持系统的说明信息。 @wanghaile 谢谢建议 😸 

![image](https://user-images.githubusercontent.com/1063891/30002371-2b92255a-90da-11e7-926a-cb5c9dedd2f3.png)
