### ISSUE TITLE
show-busy-java-threads.sh cpu占用不准确

### ISSUE THREAD

**Issue by qsLI** [oldratlee/useful-scripts#67]
ps aux是根据各类时间算出的cpu占用率，top是实时的！

http://xiaorui.cc/2017/04/26/%E7%BA%A0%E7%BB%93ps%E5%92%8Ctop%E7%9A%84cpu%E5%8D%A0%E7%94%A8%E7%8E%87%E4%B8%8D%E4%B8%80%E8%87%B4%E9%97%AE%E9%A2%98/

可以使用  top -H -p 来计算各个线程的cpu时间

**Comment by oldratlee** [comment]
收到，@qsLI

在查一下top如何方便的用脚本来调用，以完成这个功能的实现

- #23 ( @sdslnmd ) 也提了这个问题

**Comment by oldratlee** [comment]
@qsLI @sdslnmd (#23) 实现好了，使用`top`命令来获取线程的CPU占用率。

当然，可以使用选项`-P, --use-ps`，来指定还是用`ps`命令获取线程的CPU占用率。

```bash
# 帮助信息
$ show-busy-java-threads -h
Usage: show-busy-java-threads [OPTION]... [delay [count]]
Find out the highest cpu consumed threads of java, and print the stack of these threads.

Example:
  show-busy-java-threads       # show busy java threads info
  show-busy-java-threads 1     # update every 1 second, (stop by eg: CTRL+C)
  show-busy-java-threads 3 10  # update every 3 seconds, update 10 times

Options:
  -p, --pid <java pid>      find out the highest cpu consumed threads from the specifed java process,
                            default from all java process.
  -c, --count <num>         set the thread count to show, default is 5
  -a, --append-file <file>  specify the file to append output as log
  -P, --use-ps              use ps command to find busy thead(cpu usage) instead of top command,
                            default use top command, because cpu usage of ps command is expressed as
                            the percentage of time spent running during the entire lifetime of a process,
                            this is not ideal.
  -s, --jstack-path <path>  specify the path of jstack command
  -F, --force               set jstack to force a thread dump
                            use when jstack <pid> does not respond (process is hung)
  -m, --mix-native-frames   set jstack to print both java and native frames (mixed mode)
  -l, --lock-info           set jstack with long listing. Prints additional information about locks
  -h, --help                display this help and exit
  delay                     the delay between updates in seconds
  count                     the number of updates
                            delay/count arguments imitates the style of vmstat command
```


更多详见文档：

https://github.com/oldratlee/useful-scripts/blob/master/docs/java.md#beer-show-busy-java-threads

**Comment by oldratlee** [comment]
# 关于系统`CPU`信息收集的相关资料

- [纠结ps和top的cpu占用率不一致问题](http://xiaorui.cc/2017/04/26/%E7%BA%A0%E7%BB%93ps%E5%92%8Ctop%E7%9A%84cpu%E5%8D%A0%E7%94%A8%E7%8E%87%E4%B8%8D%E4%B8%80%E8%87%B4%E9%97%AE%E9%A2%98/)
- [Monitoring CPU Usage In Multithreaded Applications](http://blog.audio-tk.com/2008/10/16/monitoring-cpu-usage-in-multithreaded-applications/)
- [Calculate CPU% by process from /proc/stat and /proc/<pid>/stat](https://codereview.stackexchange.com/questions/67904/calculate-cpu-by-process-from-proc-stat-and-proc-pid-stat)
- [Retrieve CPU usage and memory usage of a single process on Linux?
Ask Question](https://stackoverflow.com/questions/1221555/retrieve-cpu-usage-and-memory-usage-of-a-single-process-on-linux)
- [Top实践小技巧](http://kumu-linux.github.io/blog/2013/06/07/top-hacks/)
- [Linux top命令详解和使用技巧](http://blog.51cto.com/fuwenchao/1342748)
- [linux top 命令详细介绍（示例、参数、快捷键）](http://blog.51cto.com/dwlinux/721613)
-  [How to get %CPU usage of a process - linuxquestions.org](https://www.linuxquestions.org/questions/linux-newbie-8/how-to-get-cpu-usage-of-a-process-63726/)

**Comment by qsLI** [comment]
赞!
