### ISSUE TITLE
show-busy-java-threads#__top_threadId_cpu在top v3.2下提取不正确

### ISSUE THREAD

**Issue by geekMessi** [oldratlee/useful-scripts#71]
```bash
HOME="$tmp_store_dir" top -H -b -d $top_delay -n 2 |
    awk '{
            if (idx == 3 && $NF == "java")    # $NF is command
                # only print 4th text block(idx == 3), aka. process info of second top update
                print $1 " " $9    # $1 is thread id, $9 is %cpu
            if ($0 == "")
                idx++
    }' | sort -k2,2nr
```
这部分逻辑是不是有些问题？为什么只抓4th? 执行了一下，没有输出
改成下面是OK的

```bash
HOME="$tmp_store_dir" top -H -b -d $top_delay -n 2 |
    awk '{
            if ($NF == "java")    # $NF is command
                # only print 4th text block(idx == 3), aka. process info of second top update
                print $1 " " $9    # $1 is thread id, $9 is %cpu
    }' | sort -k2,2nr
```

awk语句

**Comment by oldratlee** [comment]
@geekMessi  实现后自己测试了多次。

给一下

1. 你的环境信息
1. 运行方式、运行过程 和 运行结果

另外，如果上面的你问题定位对的，已经缩到上面的范围：

可以分段运行并给一下结果，可以比较容易的定位和Fix问题：

1. `top -H -b -d 0.5 -n 2`
2. ```top -H -b -d 0.5 -n 2 |
        awk '{
                if (idx == 3 && $NF == "java")    # $NF is command
                    # only print 4th text block(idx == 3), aka. process info of second top update
                    print $1 " " $9    # $1 is thread id, $9 is %cpu
                if ($0 == "")
                    idx++
        }' ```

**Comment by geekMessi** [comment]
top -v
	top: procps version 3.2.8
awk --version
      GNU Awk 3.1.7

```
top -H -b -d 0.5 -n 2 | tee top.out |
        awk '{
                if (idx == 3)    # $NF is command
                    # only print 4th text block(idx == 3), aka. process info of second top update
                    print "4th ? --> : N1-" $1 ", N9-" $9 ", NF-"$NF    # $1 is thread id, $9 is %cpu
                if ($0 == ""){
                    print idx
                    idx++
                }

        } END { print idx} '
```

output:
```
1
2
4th ? --> : N1-top, N9-user,, NF-0.14
4th ? --> : N1-Tasks:, N9-stopped,, NF-zombie
4th ? --> : N1-Cpu(s):, N9-0.0%st, NF-0.0%st
4th ? --> : N1-Mem:, N9-buffers, NF-buffers
4th ? --> : N1-Swap:, N9-cached, NF-cached
4th ? --> : N1-, N9-, NF-
3
4
5
```

**Comment by oldratlee** [comment]
给一下 top的输出， 即 `top.out` 文件  @geekMessi 

可以 在  [oldratlee/useful-scripts - gitter.im](https://gitter.im/oldratlee/useful-scripts?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) 聊

**Comment by oldratlee** [comment]
已确定问题：  两次Top的输出之间， `top v3.2` 有2个空行。

**Comment by oldratlee** [comment]
写了个实现，Fix了一下，

#72  show-duplicate-java-classes support command name jsvc to find java process feature
这个的支持也加了

你试试是不是 OK 的？ ❤️ @geekMessi

**Comment by oldratlee** [comment]
@geekMessi OK 🎉
