### ISSUE TITLE
执行提示语法错误 13行 Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by niuniu9631** [oldratlee/useful-scripts#75]
show-busy-java-threads.sh
本地环境测试都是可以使用的，放到线上去就提示错误，烦请大神指点
test.sh: 13: test.sh: Syntax error: "(" unexpected

**Comment by oldratlee** [comment]
给一下 你的运行方式。  @niuniu9631 

更多 排查 和 报问题要提供的信息 参见 https://github.com/oldratlee/useful-scripts/issues/57

**Comment by niuniu9631** [comment]
这一行提示的错误
readonly -a COMMAND_LINE=("$0" "$@")
运行方式：
进入所在目录 执行
sh test.sh
线上用的是阿里云ECS服务器

**Comment by niuniu9631** [comment]
多谢。

**Comment by oldratlee** [comment]
> https://github.com/oldratlee/useful-scripts/issues/57#issuecomment-326485965 ：
>
> 尽量不要自己去指定`sh`的方式去执行脚本 @wanghaile (这个是坏习惯 😄 ) ：
> 1. 脚本已经是可执行模式的，在里面指定的是`bash`，操作更简单些。  
>   脚本中总是声明上确定的`shell`（如`bash`）是好的实践： `#!/bin/bash`。
> 2. 不同的`shell`（sh、bash、zsh、fish、csh、tcsh、ksh、ash、dash……）有各种差异，深坑勿入。
>    目前主流的是`bash`/`zsh`。
>    更多`shell`的信息 参见 https://en.wikipedia.org/wiki/Comparison_of_command_shells
> 3. `sh`可能是个符号链接，可能链接到不同的`shell`，如有的`Ubuntu`版本，`sh`是链接到`dash`的。

简单地说，用`sh`运行是个深坑，勿入！
\# 原因见上面的说明。 @niuniu9631  

#### 推荐直接执行的方式：

```bash
wget https://github.com/oldratlee/useful-scripts/raw/master/show-busy-java-threads
chmod +x show-busy-java-threads
./show-busy-java-threads
```

**Comment by niuniu9631** [comment]
恩，采用大神推荐的方式执行成功了，太感谢了
