### ISSUE TITLE
文件名称问题

### ISSUE THREAD

**Issue by 595979101** [oldratlee/useful-scripts#79]
麻烦问下用了那个`show-busy-java-threads`  

启动命令这样 `./show-busy-java-threads 3 -c 3 -S /usr/local/logs/` 

为啥输出的文件名称 不是按照日期命名啊？

**Comment by 595979101** [comment]
2019-05-05_17:34:06.645529824_1_ps
-rw-r--r--. 1 root root  48504 5月   5 17:34 2019-05-05_17:34:06.645529824_1_top
-rw-r--r--. 1 root root   2007 5月   5 17:34 2019-05-05_17:34:06.645529824_2_ps
-rw-r--r--. 1 root root  48504 5月   5 17:34 2019-05-05_17:34:06.645529824_2_top
-rw-r--r--. 1 root root   2007 5月   5 17:34 2019-05-05_17:34:06.645529824_3_ps
-rw-r--r--. 1 root root  48504 5月   5 17:34 2019-05-05_17:34:06.645529824_3_top
-rw-r--r--. 1 root root   2007 5月   5 17:35 2019-05-05_17:34:06.645529824_4_ps
-rw-r--r--. 1 root root  48504 5月   5 17:35 2019-05-05_17:34:06.645529824_4_top
-rw-r--r--. 1 root root   2007 5月   5 17:35 2019-05-05_17:34:06.645529824_5_ps
-rw-r--r--. 1 root root  48346 5月   5 17:35 2019-05-05_17:34:06.645529824_5_top
-rw-r--r--. 1 root root   2007 5月   5 17:35 2019-05-05_17:34:06.645529824_6_ps
-rw-r--r--. 1 root root  48346 5月   5 17:35 2019-05-05_17:34:06.645529824_6_top
-rw-r--r--. 1 root root   2007 5月   5 17:36 2019-05-05_17:34:06.645529824_7_ps
-rw-r--r--. 1 root root  48504 5月   5 17:36 2019-05-05_17:34:06.645529824_7_top
-rw-r--r--. 1 root root   3843 5月   5 17:36 2019-05-05_17:34:06.645529824_show-busy-java-threads

**Comment by oldratlee** [comment]
> 为啥输出的文件名称 不是按照日期命名啊？

这样细粒度时间的文件（不按日期命名） 是为了：
每一次的运行的结果 都在 独立的文件中，以方便逐个查看。

说的一下 你的碰到的问题 和 需求？  :)
