### ISSUE TITLE
show-busy-java-threads能否支持检测docker容器里的java服务

### ISSUE THREAD

**Issue by keketrtr** [oldratlee/useful-scripts#83]
如果可以支持docker，希望可以分享一下用法和案例，谢谢！

**Comment by oldratlee** [comment]
> 如果可以支持docker

好想法。 👍 

> 可以分享一下用法和案例

- 你可以搜索一下，有`show-busy-java-threads`的文章  和  排查`Java CPU`的文章。
- 这个脚本功能明确，使用起来解决问题即可。

**Comment by oldratlee** [comment]
@keketrtr 

实现了 一个`Docker`使用的便利脚本 `cp-into-docker-and-run`：
- 拷贝本机的执行文件到指定的`docker container`中并在`docker container`中执行：
- 文档：https://github.com/oldratlee/useful-scripts/blob/dev-2.x/docs/shell.md#-cp-into-docker-and-run

通过这个脚本来运行`show-busy-java-threads`，从而检测`docker`容器里的`java`服务：

```sh
$ cp-into-docker-and-run -c container_foo path/to/show-busy-java-threads

# 如果 show-busy-java-threads 已经在PATH上，可以不用指定其路径
$ cp-into-docker-and-run -c container_foo show-busy-java-threads
```
