### ISSUE TITLE
执行报错是咋回事呀

### ISSUE THREAD

**Issue by TSlei** [oldratlee/useful-scripts#85]
![image](https://user-images.githubusercontent.com/14051097/67859974-cb1e5500-fb57-11e9-8dd7-ef07aaa50e1a.png)

**Comment by oldratlee** [comment]
不要以`sh foo-script`的方式运行脚本。 @TSlei

详细说明如下
------------

不要自己去指定`sh`的方式去执行脚本 (这个是坏习惯 😄 ) ：

1. 脚本已经是可执行模式的，在里面指定的是`bash`，操作更简单些。  
   脚本中总是指定上确定的`shell`（如`bash`）是好的实践： `#!/bin/bash`。
2. 不同的`shell`（sh、bash、zsh、fish、csh、tcsh、ksh、ash、dash……）有各种差异，深坑勿入。
    目前主流的是`bash`/`zsh`。
    更多`shell`的信息 参见 https://en.wikipedia.org/wiki/Comparison_of_command_shells
3. `sh`可能是个符号链接，可能链接到不同的`shell`，如有的`Ubuntu`版本，`sh`是链接到`dash`的。


#### 推荐直接执行的方式，如：

```bash
wget https://github.com/oldratlee/useful-scripts/raw/master/show-busy-java-threads
chmod +x show-busy-java-threads
./show-busy-java-threads
```

-------------

与 Issue https://github.com/oldratlee/useful-scripts/issues/57#issuecomment-326485965 重复。
