### ISSUE TITLE
centos 6 版本 show-busy-java-threads 没有打印出来问题线程

### ISSUE THREAD

**Issue by janecms** [oldratlee/useful-scripts#88]
个人造了一个消耗CPU的例子，使用“show-busy-java-threads”脚本。发现没有打印出来问题线程
```
[root@localhost bin]# ./show-busy-java-threads
[1] Busy(0.0%) thread(2351/0x92f) stack of java process(2351) under user(root):

[2] Busy(0.0%) thread(2352/0x930) stack of java process(2351) under user(root):
"DestroyJavaVM" #30 prio=5 os_prio=0 tid=0x00007f989804b000 nid=0x930 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
```

是需要安装什么工具吗？我是用的是centos CentOS-6.10-x86_64-minimal.iso

**Comment by oldratlee** [comment]
从上面的输出来看，已经输出了一些线程的信息，说明 `jstack`命令已经找到了。

按下面的方式 查看 并提供一些信息： @janecms 

1. 『个人造了一个消耗CPU的例子』，先检查你的`CPU`消耗是否制造成功，用`top`看看
    如果`CPU`消耗造成功了，继续下面
1. 用下面的方式运行

    ```bash
    bash -x ./show-busy-java-threads -S infos
    ```
    - `bash -x`方式运行输出执行过程
        你检查看看，并提供输出的信息
    - 中间的命令的输出信息（如`top`）在指定的`infos`目录
        你检查看看，提供一下
