### ISSUE TITLE
show-busy-java-threads 重复执行支不支持 -p

### ISSUE THREAD

**Issue by yxb-git** [oldratlee/useful-scripts#89]
show-busy-java-threads能否支持检测docker容器里的java服务

**Comment by oldratlee** [comment]
> show-busy-java-threads 重复执行支不支持 -p

`-p --pid`选项指定show的java进程，可以与重复执行一起使用的。
你自己也可以试一下确定。 @yxb-git 

> show-busy-java-threads能否支持检测docker容器里的java服务
 与 #83 重复。 欢迎贡献来实现 ❤️ @yxb-git
