### ISSUE TITLE
能实现windows版本吗？

### ISSUE THREAD

**Issue by sky-daiji** [oldratlee/useful-scripts#90]
我的java应用部署在windows系统上

**Comment by oldratlee** [comment]
`Windows`版本 是指实现`cmd bat`吗？
因为`bat`我不熟悉，有些困难。

当然欢迎你实现与贡献 😄  @sky-daiji

**Comment by oldratlee** [comment]
Windows官方支持了[`WSL`(`Windows Subsystem for Linux`)](https://docs.microsoft.com/en-us/windows/wsl/about)。

通过`WSL`，可以有`Linux`环境（如`Bash`及其相关命令工具），以运行这个库的脚本。
不专门实现`Windows`版本了。  @sky-daiji
