### ISSUE TITLE
Unknown Source

### ISSUE THREAD

**Issue by myysophia** [oldratlee/useful-scripts#99]
![image](https://user-images.githubusercontent.com/25994521/125768610-afc9870f-3664-40c3-8ec3-d81052c79a18.png)
这个分析出来出现 “”Unknown Source”， 请问是什么问题？

**Comment by oldratlee** [comment]
> 这个分析出来出现 “”Unknown Source”， 请问是什么问题？

这一行对应`lambda`。
对于`lambda`，`JVM`/`jstack`可能就是不能显示出代码行。 @myysophia 
由`JVM`/`jstack`工具决定，`show-busy-java-threads`只是调用这个工具。
